server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location = /tasks {
    default_type application/json;
    try_files /api/tasks.json =404;
  }

  location = /market-feed {
    default_type application/json;
    try_files /api/market-feed.json =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
